name: Deploy to iFastNet

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /public_html/scratchnews.freedev.app/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/schema.sql
            **/brevo_debug.log
            **/assets/uploads/**